export {
  getMaterialSystemPrompt,
  getSkillSystemPrompt,
  getWorkspaceSystemPrompt,
  readMaterialAgentPromptTemplate,
  readMaterialAgentPromptTemplateForType,
  readMaterialPromptTemplate,
  readSkillAgentPromptTemplate,
  readSkillAgentPromptTemplateForType,
  readWorkspaceAgentPromptTemplate,
  resetMaterialAgentPromptOverride,
  resetMaterialPromptOverride,
  resetSkillAgentPromptOverride,
  resetWorkspaceAgentPromptOverride,
  saveMaterialAgentPromptOverride,
  saveMaterialPromptOverride,
  saveSkillAgentPromptOverride,
  saveWorkspaceAgentPromptOverride,
} from './legacy'
