export type {
  Book,
  BookStatus,
  BookSummary,
  BookType,
  ExpertDraft,
  ExpertDraftCharacterState,
  ExpertDraftSection,
  MemoryEntry,
  MemoryTag,
  LongStageId,
  ScriptStageId,
  ShortStageId,
  StageId,
} from './workspaceCore'

export {
  MEMORY_TAGS,
  SCRIPT_GENRE_OPTIONS,
  SHORT_GENRE_OPTIONS,
  WORKSPACE_CONTENT_STAGES,
  WORKSPACE_STAGES,
  bookTypeLabel,
  defaultExpertDraft,
  isWorkspaceBook,
  isWorkspaceShortBook,
  mergeStagePatchIntoAll,
  normalizeAllBookStages,
  normalizeExpertDraft,
  normalizeMemoryEntries,
  normalizeMemoryTag,
  normalizeStages,
  normalizeStagesForWorkspaceBook,
  resolveWorkspaceContentStagesForBook,
  resolveWorkspaceBookGenre,
  resolveWorkspaceStagesForBook,
} from './workspaceCore'

export type {
  AiModelConfig,
  AiModelDefaults,
  AiModelSettings,
  AppearanceStyle,
  ImageModelConfig,
  Material,
  MaterialKind,
  MaterialKindWithMixed,
  MaterialPromptKind,
  MaterialStageId,
  MaterialSummary,
  MaterialType,
  SaveBookOptions,
  SaveMaterialOptions,
  SaveSkillOptions,
  Skill,
  SkillKind,
  SkillStageEntry,
  SkillStageId,
  SkillSummary,
  SkillType,
  WorkspaceAgentReadAccessConfig,
  WorkspaceAgentReadAccessEntry,
  WorkspaceAgentId,
} from '../bridge'

export {
  APPEARANCE_STYLE_STORAGE_KEY,
  LIBRARY_TYPE_LABELS,
  MATERIAL_MANAGER_AGENT_ID,
  MATERIAL_MANAGER_PROMPT_KIND,
  MATERIAL_KIND_KEYS,
  MATERIAL_KIND_LABELS,
  MATERIAL_KIND_STAGE_IDS,
  MATERIAL_STAGE_LABELS,
  MATERIAL_STAGE_KIND,
  SCRIPT_MATERIAL_GENRES,
  SHORT_MATERIAL_GENRES,
  SKILL_MANAGER_AGENT_ID,
  SKILL_MANAGER_PROMPT_KIND,
  SKILL_KIND_KEYS,
  SKILL_KIND_LABELS,
  SKILL_KIND_STAGE_IDS,
  SKILL_STAGE_KEYS,
  SKILL_STAGE_LABELS,
  TEXT_MODEL_API_KEY_PLACEHOLDER,
  WORKSPACE_AGENT_READ_ACCESS_STORAGE_KEY,
  WORKSPACE_ROOT_STORAGE_KEY,
  emptyLinkedMaterialIdsByKind,
  emptyLinkedSkillIdsByKind,
  firstLinkedMaterialId,
  firstLinkedSkillId,
  getMaterialParentGenres,
  getMaterialSubGenres,
  libraryTypeLabel,
  materialMatchesKind,
  materialMetaLabel,
  materialTypeLabel,
  normalizeAiModelSettings,
  normalizeAppearanceStyle,
  normalizeBookStatus,
  normalizeBookType,
  normalizeLinkedMaterialIdsByKind,
  normalizeLinkedSkillIdsByKind,
  normalizeMaterialKind,
  normalizeMaterialStages,
  normalizeMaterialType,
  normalizeSkillStageId,
  normalizeSkillStages,
  normalizeSkillType,
  skillMatchesKind,
  resolveMaterialParentGenre,
  skillTypeLabel,
  createEmptyMemory,
  getBookMemories,
  getUserMemories,
  mergeUniqueMemories,
  saveBookMemories,
  saveUserMemories,
} from '../bridge'

export type {
  WorkspaceDefinition,
  WorkspaceStageDefinition,
  WorkspaceType,
} from '../workspaces/registry'

export {
  WORKSPACE_DEFINITIONS,
  getWorkspaceDefinition,
  isWorkspaceTypeEnabled,
  normalizeWorkspaceType,
} from '../workspaces/registry'
